departments_list = ["auvergne-rhone-alpes",
                    "bourgogne-franche-comte",
                    "bretagne",
                    "centre-val-de-loire",
                    "ajaccio-bastia-corse",
                    "grand-est",
                    "hauts-de-france",
                    "ile-de-france",
                    "normandie",
                    "nouvelle-aquitaine",
                    "occitanie",
                    "pays-de-la-loire",
                    "provence-alpes-cote-dazur",
                    "outre-mer",
                    "belgique",
                    "suisse",
                    "luxembourg"]
